### ISSUE TITLE
请问支持用typescript写的 .vue 组件吗？

### ISSUE THREAD

**Issue by KakashiZs** [sillyY/vuepress-plugin-code-segment#1]
请问支持用typescript写的 .vue 组件吗？
现在有个需求是想要把用 ts 写的组件和源码用 vuepress展示出来，也尝试使用过 demo-block 和 demo-code 插件，前者不支持typescript 写的vue组件，后者使用 vuepress-plugin-typescript 之后可以支持，但缺点是会共享 data 。请问这个项目可以满足这个需求吗？谢谢~

**Comment by sillyY** [comment]
抱歉，这么久才回复。目前该项目暂不支持typescript，稍等，我会尽快支持。
欢迎你帮忙解决该问题，谢谢!
